#include "nsISupports.idl"
#include "otIPipeline.idl"

interface otICodecService;
interface otISource;

[scriptable, uuid(9fb428af-5d1e-4f0a-820f-e26de975fc88)]
interface otICodecInfo : nsISupports
{
  readonly attribute otICodecService service;
  readonly attribute string name;
  readonly attribute unsigned short payloadId;
  readonly attribute unsigned long clockrate;
  readonly attribute unsigned short channels;
  readonly attribute unsigned short ptime;
  readonly attribute unsigned short maxptime;
};

[scriptable, uuid(5f785bd1-2fd9-418c-a65b-01b3e01fc595)]
interface otICodecService : nsISupports
{
/*  void getMedias(inout short firstFreePayloadId,
                 [array, size_is(count)] out otICodecInfo medias,
                 out unsigned long count);*/

  otISource createEncoder();
  otISource createDecoder();
};

%{C++

#define OT_CODEC_CONTRACTID "@process-one.net/codec;1"
#define OT_CODEC_CONTRACTID_PREFIX OT_CODEC_CONTRACTID "?type="

#define OT_CODEC_CID \
{ /* a99b04bc-08ca-11df-b379-002268a81ba7 */ \
  0xa99b04bc, \
  0x08ca, \
  0x11df, \
  {0xb3, 0x79, 0x00, 0x22, 0x68, 0xa8, 0x1b, 0xa7 } \
}

%}
