#include "nsISupports.idl"

[scriptable, uuid(fb27dd34-99d2-4051-abc7-e633d9254a21)]
interface otISystrayListener : nsISupports
{
    void onMouseClick(in long screenX, in long screenY, in long windowX, in long windowY,
                      in long clicksCount, in boolean ctrlKey, in boolean altKey,
                      in boolean shiftKey, in boolean metaKey, in unsigned short button);
};

[scriptable, uuid(f6536e27-b4e0-4b1b-a604-589da025b2c4)]
interface otISystray : nsISupports
{
    attribute nsISupports icon;
    attribute AString tooltip;

    void init(in otISystrayListener listener);

    void show();
    void hide();
};

%{C++

#define OT_SYSTRAY_CONTRACTID "@process-one.net/systray;1"

#define OT_SYSTRAY_CID \
{ /* b9e86108-eece-4309-8465-4421d13343f6 */ \
  0xb9e86108, \
  0xeece, \
  0x4309, \
  {0x84, 0x65, 0x44, 0x21, 0xd1, 0x33, 0x43, 0xf6 } \
}

%}

